const photos = [
    { src: 'http://pic.yupoo.com/yehorlapko/3a9aed50/5e0bbbcd.jpg',
      srcBig: 'http://pic.yupoo.com/yehorlapko/c67524e0/5364ec16.jpg',
      category: 'compart',
      index: 0,
      title: '',
      position: 'compart column 1' 
    },
    { src: 'http://pic.yupoo.com/yehorlapko/217651f2/b3b03386.jpg',
      srcBig: 'http://pic.yupoo.com/yehorlapko/2bc71ba9/0676f4a7.jpg',
      category: 'compart',
      index: 1,
      title: '',
      position: 'compart column 1' 
    },
    { src: 'http://pic.yupoo.com/yehorlapko/9af55fb9/f8daf229.jpg',
      srcBig: 'http://pic.yupoo.com/yehorlapko/3508377b/c3fd1a2c.jpg',
      category: 'compart',
      index: 2,
      title: '',
      position: 'compart column 1' 
    },
    { src: 'http://pic.yupoo.com/yehorlapko/0c1fef68/0eebf97e.jpg',
      srcBig: 'http://pic.yupoo.com/yehorlapko/7363b14c/423fdf79.jpg',
      category: 'compart',
      index: 3,
      title: '',
      position: 'compart column 1' 
    },
    { src: 'http://pic.yupoo.com/yehorlapko/0f9970c3/89f35def.jpg',
      srcBig: 'http://pic.yupoo.com/yehorlapko/01a4cb5e/257234bb.jpg',
      category: 'compart',
      index: 4,
      title: '',
      position: 'compart column 1' 
    },
    { src: 'http://pic.yupoo.com/yehorlapko/3db5dd7f/82a85b79.jpg',
      srcBig: 'http://pic.yupoo.com/yehorlapko/92739ce1/b419ace9.jpg',
      category: 'compart',
      index: 5,
      title: '',
      position: 'compart column 1' 
    },
    { src: 'http://pic.yupoo.com/yehorlapko/a02f03bb/f7077f8d.jpg',
      srcBig: 'http://pic.yupoo.com/yehorlapko/f60298c3/f1e762c3.jpg',
      category: 'compart',
      index: 6,
      title: '',
      position: 'compart column 1' 
    },
    { src: 'http://pic.yupoo.com/yehorlapko/5025cbe9/12a3c2c4.jpg',
      srcBig: 'http://pic.yupoo.com/yehorlapko/6dc642fa/92d81dfe.jpg',
      category: 'compart',
      index: 7,
      title: '',
      position: 'compart column 1' 
    },
    { src: 'http://pic.yupoo.com/yehorlapko/fad06da9/0520124f.jpg',
      srcBig: 'http://pic.yupoo.com/yehorlapko/b571aed7/c91b076c.jpg',
      category: 'compart',
      index: 8, 
      title: '',
      position: 'compart column 1'
    },
    { src: 'http://pic.yupoo.com/yehorlapko/aef29093/d6c92e1c.jpg',
      srcBig: 'http://pic.yupoo.com/yehorlapko/71d8ba97/520ae327.jpg',
      category: 'compart',
      index: 9, 
      title: '',
      position: 'compart column 1'
    },
    { src: 'http://pic.yupoo.com/yehorlapko/50fb6635/a84f4a55.jpg',
      srcBig: 'http://pic.yupoo.com/yehorlapko/1cc26fb4/55dc8637.jpg',
      category: 'compart',
      index: 10, 
      title: '',
      position: 'compart column 1'
    },
    { src: 'http://pic.yupoo.com/yehorlapko/193cb7a5/ef1cd8e6.jpg',
      srcBig: 'http://pic.yupoo.com/yehorlapko/30e3ac82/5806c0fb.jpg',
      category: 'compart',
      index: 11, 
      title: '',
      position: 'compart column 1'
    },
    { src: 'http://pic.yupoo.com/yehorlapko/4144a494/b8c8ba59.jpg',
      srcBig: 'http://pic.yupoo.com/yehorlapko/8c4b0797/6ceb2355.jpg',
      category: 'compart',
      index: 12, 
      title: '',
      position: 'compart column 1'
    },
    { src: 'http://pic.yupoo.com/yehorlapko/1aeb20c4/2d72a627.jpg',
      srcBig: 'http://pic.yupoo.com/yehorlapko/41c4150e/242baa8d.jpg',
      category: 'compart',
      index: 13, 
      title: '',
      position: 'compart column 2'
    },
    { src: 'http://pic.yupoo.com/yehorlapko/fbdd9e11/8cb4cb49.jpg',
      srcBig: 'http://pic.yupoo.com/yehorlapko/853ea768/bdd3e66e.jpg',
      category: 'compart',
      index: 14, 
      title: '',
      position: 'compart column 2'
    },
    { src: 'http://pic.yupoo.com/yehorlapko/00f1f41a/6e38d173.jpg',
      srcBig: 'http://pic.yupoo.com/yehorlapko/8dd9a90c/670c7cf9.jpg',
      category: 'compart',
      index: 15, 
      title: '',
      position: 'compart column 2'
    },
    { src: 'http://pic.yupoo.com/yehorlapko/801693ca/55e682f7.jpg',
      srcBig: 'http://pic.yupoo.com/yehorlapko/383a9ebb/2e6c0d20.jpg',
      category: 'compart',
      index: 16, 
      title: '',
      position: 'compart column 2'
    },
    { src: 'http://pic.yupoo.com/yehorlapko/29311811/3fad441d.jpg',
      srcBig: 'http://pic.yupoo.com/yehorlapko/29614eb3/cede51f6.jpg',
      category: 'compart',
      index: 17, 
      title: '',
      position: 'compart column 2'
    },
    { src: 'http://pic.yupoo.com/yehorlapko/e540c40f/50165aa1.jpg',
      srcBig: 'http://pic.yupoo.com/yehorlapko/ac0ec7c2/b07c6d2a.jpg',
      category: 'compart',
      index: 18, 
      title: '',
      position: 'compart column 2'
    },
    { src: 'http://pic.yupoo.com/yehorlapko/757a837e/3247096a.jpg',
      srcBig: 'http://pic.yupoo.com/yehorlapko/9a4a2995/be09aa74.jpg',
      category: 'compart',
      index: 19, 
      title: '',
      position: 'compart column 2'
    },
    { src: 'http://pic.yupoo.com/yehorlapko/1569a3d2/17621f4c.jpg',
      srcBig: 'http://pic.yupoo.com/yehorlapko/93049df2/51601c44.jpg',
      category: 'compart',
      index: 20, 
      title: '',
      position: 'compart column 2'
    },
    { src: 'http://pic.yupoo.com/yehorlapko/5884d3a7/22f8141e.jpg',
      srcBig: 'http://pic.yupoo.com/yehorlapko/54a3468f/d27f9a3f.jpg',
      category: 'compart',
      index: 21, 
      title: '',
      position: 'compart column 2'
    },
    { src: 'http://pic.yupoo.com/yehorlapko/77488afc/09c9aa43.jpg',
      srcBig: 'http://pic.yupoo.com/yehorlapko/9ced91d7/88a4f7b4.jpg',
      category: 'compart',
      index: 22, 
      title: '',
      position: 'compart column 2'
    },
    { src: 'http://pic.yupoo.com/yehorlapko/8b200777/414afe9f.jpg',
      srcBig: 'http://pic.yupoo.com/yehorlapko/8216c2b9/3464cd06.jpg',
      category: 'compart',
      index: 23, 
      title: '',
      position: 'compart column 2'
    },
    { src: 'http://pic.yupoo.com/yehorlapko/f6ba3e43/02766168.jpg',
      srcBig: 'http://pic.yupoo.com/yehorlapko/81624a8c/f53ad7b2.jpg',
      category: 'compart',
      index: 24, 
      title: '',
      position: 'compart column 3'
    },
    { src: 'http://pic.yupoo.com/yehorlapko/d8b19523/06d56b3d.jpg',
      srcBig: '/images/image_gallery/compart/big/26smoke.jpg',
      category: 'compart',
      index: 25, 
      title: '',
      position: 'compart column 3'
    },
    { src: 'http://pic.yupoo.com/yehorlapko/ed381391/3cb52b71.jpg',
      srcBig: 'http://pic.yupoo.com/yehorlapko/9b3c0a3c/e0f4ead6.jpg',
      category: 'compart',
      index: 26, 
      title: '',
      position: 'compart column 3'
    },
    { src: 'http://pic.yupoo.com/yehorlapko/c06acfe4/941e9a02.jpg',
      srcBig: 'http://pic.yupoo.com/yehorlapko/744120c9/f51d43f7.jpg',
      category: 'compart',
      index: 27, 
      title: '',
      position: 'compart column 3'
    },
    { src: 'http://pic.yupoo.com/yehorlapko/7933f1fd/a99380b8.jpg',
      srcBig: 'http://pic.yupoo.com/yehorlapko/6402eb10/de72a256.jpg',
      category: 'compart',
      index: 28, 
      title: '',
      position: 'compart column 3'
    },
    { src: 'http://pic.yupoo.com/yehorlapko/47ea60f3/1bb9378f.jpg',
      srcBig: 'http://pic.yupoo.com/yehorlapko/2d138f19/b06b9af9.jpg',
      category: 'compart',
      index: 29, 
      title: '',
      position: 'compart column 3'
    },
    { src: 'http://pic.yupoo.com/yehorlapko/bcb3febf/7bd96030.jpg',
      srcBig: 'http://pic.yupoo.com/yehorlapko/b863d837/71910d05.jpg',
      category: 'compart',
      index: 30, 
      title: '',
      position: 'compart column 3'
    },
    { src: 'http://pic.yupoo.com/yehorlapko/0db9d941/38e7e47d.jpg',
      srcBig: 'http://pic.yupoo.com/yehorlapko/9eec7e18/6d04fd99.jpg',
      category: 'compart',
      index: 31, 
      title: '',
      position: 'compart column 3'
    },
    { src: 'http://pic.yupoo.com/yehorlapko/3b4b2a95/ad6f11cf.jpg',
      srcBig: 'http://pic.yupoo.com/yehorlapko/b6f0d3a4/013e49c7.jpg',
      category: 'compart',
      index: 32, 
      title: '',
      position: 'compart column 3'
    },
    { src: 'http://pic.yupoo.com/yehorlapko/0459ac54/dcce0cd1.jpg',
      srcBig: 'http://pic.yupoo.com/yehorlapko/b656068c/ff7fb89d.jpg',
      category: 'compart',
      index: 33, 
      title: '',
      position: 'compart column 3'
    },
    { src: 'http://pic.yupoo.com/yehorlapko/84e26d3a/e05ef7eb.jpg',
      srcBig: 'http://pic.yupoo.com/yehorlapko/3ecb96e5/37ddb35e.jpg',
      category: 'compart',
      index: 34, 
      title: '',
      position: 'compart column 3'
    },
    { src: 'http://pic.yupoo.com/yehorlapko/bd40b3ee/bbd4e6ab.jpg',
      srcBig: 'http://pic.yupoo.com/yehorlapko/dedc58b3/9b9fee2d.jpg',
      category: 'compart',
      index: 35, 
      title: '',
      position: 'compart column 3'
    },
    { src: 'http://pic.yupoo.com/yehorlapko/a1f7f2fd/da4506c3.jpg',
      srcBig: 'http://pic.yupoo.com/yehorlapko/a1300524/d7a789bf.jpg',
      category: 'bw',
      index: 36,
      title: '',
      position: 'bw column 1'
    },
    { src: 'http://pic.yupoo.com/yehorlapko/b5f093b3/d9386a7d.jpg',
      srcBig: 'http://pic.yupoo.com/yehorlapko/908ec593/7841240e.jpg',
      category: 'bw',
      index: 37,
      title: '',
      position: 'bw column 1'
    },
    { src: 'http://pic.yupoo.com/yehorlapko/9664f69c/cc0a973a.jpg',
      srcBig: 'http://pic.yupoo.com/yehorlapko/d05659c9/495d4b96.jpg',
      category: 'bw',
      index: 38,
      title: '',
      position: 'bw column 1'
    },
    { src: 'http://pic.yupoo.com/yehorlapko/de8e91dd/e46d62e5.jpg',
      srcBig: 'http://pic.yupoo.com/yehorlapko/59658339/af6e0704.jpg',
      category: 'bw',
      index: 39,
      title: '',
      position: 'bw column 1'
    },
    { src: 'http://pic.yupoo.com/yehorlapko/0a95574c/b62441eb.jpg',
      srcBig: 'http://pic.yupoo.com/yehorlapko/11f50845/f1de692b.jpg',
      category: 'bw',
      index: 40,
      title: '',
      position: 'bw column 2'
    },
    { src: 'http://pic.yupoo.com/yehorlapko/8ee5fa10/621bb521.jpg',
      srcBig: 'http://pic.yupoo.com/yehorlapko/63ce9874/1aaf998f.jpg',
      category: 'bw',
      index: 41,
      title: '',
      position: 'bw column 2'
    },
    { src: 'http://pic.yupoo.com/yehorlapko/1a2d5548/960f2daa.jpg',
      srcBig: 'http://pic.yupoo.com/yehorlapko/d2db1caa/a630b1d7.jpg',
      category: 'bw',
      index: 42,
      title: '',
      position: 'bw column 2'
    },
    { src: 'http://pic.yupoo.com/yehorlapko/8ae8033a/2aef6d74.jpg',
      srcBig: 'http://pic.yupoo.com/yehorlapko/70f7da38/1c53e85b.jpg',
      category: 'bw',
      index: 43,
      title: '',
      position: 'bw column 2'
    },
    { src: 'http://pic.yupoo.com/yehorlapko/c65539f1/38d570b0.jpg',
      srcBig: 'http://pic.yupoo.com/yehorlapko/5be316f9/3c54b181.jpg',
      category: 'bw',
      index: 44,
      title: '',
      position: 'bw column 3'
    },
    { src: 'http://pic.yupoo.com/yehorlapko/88d6d5ed/fe15e3c2.jpg',
      srcBig: 'http://pic.yupoo.com/yehorlapko/0683bf2b/a71b7e73.jpg',
      category: 'bw',
      index: 45,
      title: '',
      position: 'bw column 3'
    },
    { src: 'http://pic.yupoo.com/yehorlapko/442a0ae6/614b1dde.jpg',
      srcBig: 'http://pic.yupoo.com/yehorlapko/006dea15/9c97c43c.jpg',
      category: 'bw',
      index: 46,
      title: '',
      position: 'bw column 3'
    },
    { src: 'http://pic.yupoo.com/yehorlapko/ade34396/c0a1c4bd.jpg', 
      srcBig: 'http://pic.yupoo.com/yehorlapko/e195d7f9/0bdac779.jpg',
      category: 'bw',
      index: 47,
      title: '',
      position: 'bw column 3'
    },
    { src: 'http://pic.yupoo.com/yehorlapko/0ecb1936/c6600df3.jpg', 
      srcBig: 'http://pic.yupoo.com/yehorlapko/47544b41/179e7659.jpg', 
      category: 'bw' ,
      index: 48,
      title: '',
      position: 'bw column 2'
    },
    { src: 'http://pic.yupoo.com/yehorlapko/203a264a/7963de83.jpg', 
      srcBig: 'http://pic.yupoo.com/yehorlapko/f6b9a3bf/93ea1fcc.jpg',
      category: 'portraits' ,
      index: 49,
      title: '',
      position: 'portraits column 1'
    },
    { src: 'http://pic.yupoo.com/yehorlapko/ea0e13a7/4f603d30.jpg', 
      srcBig: 'http://pic.yupoo.com/yehorlapko/8b3f8d30/1484a400.jpg', 
      category: 'portraits' ,
      index: 50,
      title: '',
      position: 'portraits column 1'
    },
    { src: 'http://pic.yupoo.com/yehorlapko/e1062a0c/467af7cf.jpg', 
      srcBig: 'http://pic.yupoo.com/yehorlapko/c5c752e2/d04871f9.jpg', 
      category: 'portraits' ,
      index: 51,
      title: '',
      position: 'portraits column 1'
    },
    { src: 'http://pic.yupoo.com/yehorlapko/8d47c92a/a2157777.jpg', 
      srcBig: 'http://pic.yupoo.com/yehorlapko/1cdcae88/46694f8f.jpg',
      category: 'portraits' ,
      index: 52,
      title: '',
      position: 'portraits column 1'
    },
    { src: 'http://pic.yupoo.com/yehorlapko/ae6fab31/948183b4.jpg', 
      srcBig: 'http://pic.yupoo.com/yehorlapko/4943550b/48398713.jpg',
      category: 'portraits' ,
      index: 53,
      title: '',
      position: 'portraits column 1'
    },
    { src: 'http://pic.yupoo.com/yehorlapko/0d16865c/0084c1a0.jpg', 
      srcBig: 'http://pic.yupoo.com/yehorlapko/f3b872a2/702025d3.jpg',
      category: 'portraits' ,
      index: 54,
      title: '',
      position: 'portraits column 2'
    },
    { src: 'http://pic.yupoo.com/yehorlapko/91a66b7c/66caea85.jpg', 
      srcBig: 'http://pic.yupoo.com/yehorlapko/96d3dae8/bcb655b6.jpg',
      category: 'portraits' ,
      index: 55,
      title: '',
      position: 'portraits column 2'
    },
    { src: 'http://pic.yupoo.com/yehorlapko/c13bad90/eeea774c.jpg', 
      srcBig: 'http://pic.yupoo.com/yehorlapko/1207ab25/abbb8421.jpg',
      category: 'portraits' ,
      index: 56,
      title: '',
      position: 'portraits column 2'
    },
    { src: 'http://pic.yupoo.com/yehorlapko/c2c8048b/1a59a74c.jpg', 
      srcBig: 'http://pic.yupoo.com/yehorlapko/abe1f42b/dd0ce0da.jpg',
      category: 'portraits' ,
      index: 57,
      title: '',
      position: 'portraits column 2'
    },
    { src: 'http://pic.yupoo.com/yehorlapko/c9c7dbb1/56b9af23.jpg', 
      srcBig: 'http://pic.yupoo.com/yehorlapko/c193b4eb/d48791a5.jpg', 
      category: 'portraits' ,
      index: 58,
      title: '',
      position: 'portraits column 3'
    },
    { src: 'http://pic.yupoo.com/yehorlapko/403e90f9/3d9c7bf6.jpg', 
      srcBig: 'http://pic.yupoo.com/yehorlapko/1f416491/8fdd7189.jpg', 
      category: 'portraits' ,
      index: 59,
      title: '',
      position: 'portraits column 3'
    },
    { src: 'http://pic.yupoo.com/yehorlapko/816da7c8/bf0bc5b5.jpg', 
      srcBig: 'http://pic.yupoo.com/yehorlapko/b110fbec/ad6db861.jpg',
      category: 'portraits' ,
      index: 60,
      title: '',
      position: 'portraits column 3'
    },
    { src: 'http://pic.yupoo.com/yehorlapko/d1b278aa/cac6c30f.jpg', 
      srcBig: 'http://pic.yupoo.com/yehorlapko/136d899c/9cb797ef.jpg',
      category: 'portraits' ,
      index: 61,
      title: '',
      position: 'portraits column 3'
    }
  ];

  export default photos;
