const photos = [
    { src: 'https://i.imgur.com/J7VD5a9.jpg',
      srcBig: '/images/image_gallery/compart/big/1angels.jpg',
      category: 'compart',
      index: 0,
      title: '',
      position: 'compart column 1' 
    },
    { src: '/images/image_gallery/compart/2buddah.jpg',
      srcBig: '/images/image_gallery/compart/big/2buddah.jpg',
      category: 'compart',
      index: 1,
      title: '',
      position: 'compart column 1' 
    },
    { src: '/images/image_gallery/compart/3broken.jpg',
      srcBig: '/images/image_gallery/compart/big/3broken.jpg',
      category: 'compart',
      index: 2,
      title: '',
      position: 'compart column 1' 
    },
    { src: '/images/image_gallery/compart/4captain.jpg',
      srcBig: '/images/image_gallery/compart/big/4captain.jpg',
      category: 'compart',
      index: 3,
      title: '',
      position: 'compart column 1' 
    },
    { src: '/images/image_gallery/compart/5chakras.jpg',
      srcBig: '/images/image_gallery/compart/big/5chakras.jpg',
      category: 'compart',
      index: 4,
      title: '',
      position: 'compart column 1' 
    },
    { src: '/images/image_gallery/compart/6planet.jpg',
      srcBig: '/images/image_gallery/compart/big/6planet.jpg',
      category: 'compart',
      index: 5,
      title: '',
      position: 'compart column 1' 
    },
    { src: '/images/image_gallery/compart/7cocoon.jpg',
      srcBig: '/images/image_gallery/compart/big/7cocoon.jpg',
      category: 'compart',
      index: 6,
      title: '',
      position: 'compart column 1' 
    },
    { src: '/images/image_gallery/compart/8colors.jpg',
      srcBig: '/images/image_gallery/compart/big/8colors.jpg',
      category: 'compart',
      index: 7,
      title: '',
      position: 'compart column 1' 
    },
    { src: '/images/image_gallery/compart/9dance1.jpg',
      srcBig: '/images/image_gallery/compart/big/9dance1.jpg',
      category: 'compart',
      index: 8, 
      title: '',
      position: 'compart column 1'
    },
    { src: '/images/image_gallery/compart/10depression.jpg',
      srcBig: '/images/image_gallery/compart/big/10depression.jpg',
      category: 'compart',
      index: 9, 
      title: '',
      position: 'compart column 1'
    },
    { src: '/images/image_gallery/compart/11dreamcatcher.jpg',
      srcBig: '/images/image_gallery/compart/big/11dreamcatcher.jpg',
      category: 'compart',
      index: 10, 
      title: '',
      position: 'compart column 1'
    },
    { src: '/images/image_gallery/compart/12fire.jpg',
      srcBig: '/images/image_gallery/compart/big/12fire.jpg',
      category: 'compart',
      index: 11, 
      title: '',
      position: 'compart column 1'
    },
    { src: '/images/image_gallery/compart/13forest_miao.jpg',
      srcBig: '/images/image_gallery/compart/big/13forest_miao.jpg',
      category: 'compart',
      index: 12, 
      title: '',
      position: 'compart column 1'
    },
    { src: 'https://i.imgur.com/lVcUPjU.jpg',
      srcBig: '/images/image_gallery/compart/big/14future.jpg',
      category: 'compart',
      index: 13, 
      title: '',
      position: 'compart column 2'
    },
    { src: '/images/image_gallery/compart/15gym.jpg',
      srcBig: '/images/image_gallery/compart/big/15gym.jpg',
      category: 'compart',
      index: 14, 
      title: '',
      position: 'compart column 2'
    },
    { src: '/images/image_gallery/compart/16hairball.jpg',
      srcBig: '/images/image_gallery/compart/big/16hairball.jpg',
      category: 'compart',
      index: 15, 
      title: '',
      position: 'compart column 2'
    },
    { src: '/images/image_gallery/compart/17hands.jpg',
      srcBig: '/images/image_gallery/compart/big/17hands.jpg',
      category: 'compart',
      index: 16, 
      title: '',
      position: 'compart column 2'
    },
    { src: '/images/image_gallery/compart/18inside.jpg',
      srcBig: '/images/image_gallery/compart/big/18inside.jpg',
      category: 'compart',
      index: 17, 
      title: '',
      position: 'compart column 2'
    },
    { src: '/images/image_gallery/compart/19kuanYin.jpg',
      srcBig: '/images/image_gallery/compart/big/19kuanYin.jpg',
      category: 'compart',
      index: 18, 
      title: '',
      position: 'compart column 2'
    },
    { src: '/images/image_gallery/compart/20lace.jpg',
      srcBig: '/images/image_gallery/compart/big/20lace.jpg',
      category: 'compart',
      index: 19, 
      title: '',
      position: 'compart column 2'
    },
    { src: '/images/image_gallery/compart/21moonlight.jpg',
      srcBig: '/images/image_gallery/compart/big/21moonlight.jpg',
      category: 'compart',
      index: 20, 
      title: '',
      position: 'compart column 2'
    },
    { src: '/images/image_gallery/compart/22night.jpg',
      srcBig: '/images/image_gallery/compart/big/22night.jpg',
      category: 'compart',
      index: 21, 
      title: '',
      position: 'compart column 2'
    },
    { src: '/images/image_gallery/compart/23night.jpg',
      srcBig: '/images/image_gallery/compart/big/23night.jpg',
      category: 'compart',
      index: 22, 
      title: '',
      position: 'compart column 2'
    },
    { src: '/images/image_gallery/compart/24night.jpg',
      srcBig: '/images/image_gallery/compart/big/24night.jpg',
      category: 'compart',
      index: 23, 
      title: '',
      position: 'compart column 2'
    },
    { src: '/images/image_gallery/compart/25evening.jpg',
      srcBig: '/images/image_gallery/compart/big/25evening.jpg',
      category: 'compart',
      index: 24, 
      title: '',
      position: 'compart column 3'
    },
    { src: '/images/image_gallery/compart/26smoke.jpg',
      srcBig: '/images/image_gallery/compart/big/26smoke.jpg',
      category: 'compart',
      index: 25, 
      title: '',
      position: 'compart column 3'
    },
    { src: '/images/image_gallery/compart/27solar_eclipse.jpg',
      srcBig: '/images/image_gallery/compart/big/27solar_eclipse.jpg',
      category: 'compart',
      index: 26, 
      title: '',
      position: 'compart column 3'
    },
    { src: '/images/image_gallery/compart/28solitude.jpg',
      srcBig: '/images/image_gallery/compart/big/28solitude.jpg',
      category: 'compart',
      index: 27, 
      title: '',
      position: 'compart column 3'
    },
    { src: '/images/image_gallery/compart/29somewhere.jpg',
      srcBig: '/images/image_gallery/compart/big/29somewhere.jpg',
      category: 'compart',
      index: 28, 
      title: '',
      position: 'compart column 3'
    },
    { src: '/images/image_gallery/compart/30somewhere.jpg',
      srcBig: '/images/image_gallery/compart/big/30somewhere.jpg',
      category: 'compart',
      index: 29, 
      title: '',
      position: 'compart column 3'
    },
    { src: '/images/image_gallery/compart/31summer_day.jpg',
      srcBig: '/images/image_gallery/compart/big/31summer_day.jpg',
      category: 'compart',
      index: 30, 
      title: '',
      position: 'compart column 3'
    },
    { src: '/images/image_gallery/compart/32summer.jpg',
      srcBig: '/images/image_gallery/compart/big/32summer.jpg',
      category: 'compart',
      index: 31, 
      title: '',
      position: 'compart column 3'
    },
    { src: '/images/image_gallery/compart/33thaughts.jpg',
      srcBig: '/images/image_gallery/compart/big/33thaughts.jpg',
      category: 'compart',
      index: 32, 
      title: '',
      position: 'compart column 3'
    },
    { src: '/images/image_gallery/compart/34wall.jpg',
      srcBig: '/images/image_gallery/compart/big/34wall.jpg',
      category: 'compart',
      index: 33, 
      title: '',
      position: 'compart column 3'
    },
    { src: '/images/image_gallery/compart/35water.jpg',
      srcBig: '/images/image_gallery/compart/big/35water.jpg',
      category: 'compart',
      index: 34, 
      title: '',
      position: 'compart column 3'
    },
    { src: '/images/image_gallery/compart/36water.jpg',
      srcBig: '/images/image_gallery/compart/big/36water.jpg',
      category: 'compart',
      index: 35, 
      title: '',
      position: 'compart column 3'
    },
    { src: '/images/image_gallery/bw/1bw.jpg',
      srcBig: '/images/image_gallery/bw/big/1bw.jpg',
      category: 'bw',
      index: 36,
      title: '',
      position: 'bw column 1'
    },
    { src: '/images/image_gallery/bw/2bw.jpg',
      srcBig: '/images/image_gallery/bw/big/2bw.jpg',
      category: 'bw',
      index: 37,
      title: '',
      position: 'bw column 1'
    },
    { src: '/images/image_gallery/bw/3bw.jpg',
      srcBig: '/images/image_gallery/bw/big/3bw.jpg',
      category: 'bw',
      index: 38,
      title: '',
      position: 'bw column 1'
    },
    { src: '/images/image_gallery/bw/4bw.jpg',
      srcBig: '/images/image_gallery/bw/big/4bw.jpg',
      category: 'bw',
      index: 39,
      title: '',
      position: 'bw column 1'
    },
    { src: '/images/image_gallery/bw/5bw.jpg',
      srcBig: '/images/image_gallery/bw/big/5bw.jpg',
      category: 'bw',
      index: 40,
      title: '',
      position: 'bw column 2'
    },
    { src: '/images/image_gallery/bw/6bw.jpg',
      srcBig: '/images/image_gallery/bw/big/6bw.jpg',
      category: 'bw',
      index: 41,
      title: '',
      position: 'bw column 2'
    },
    { src: '/images/image_gallery/bw/7bw.jpg',
      srcBig: '/images/image_gallery/bw/big/7bw.jpg',
      category: 'bw',
      index: 42,
      title: '',
      position: 'bw column 2'
    },
    { src: '/images/image_gallery/bw/8bw.jpg',
      srcBig: '/images/image_gallery/bw/big/8bw.jpg',
      category: 'bw',
      index: 43,
      title: '',
      position: 'bw column 2'
    },
    { src: '/images/image_gallery/bw/9bw.jpg',
      srcBig: '/images/image_gallery/bw/big/9bw.jpg',
      category: 'bw',
      index: 44,
      title: '',
      position: 'bw column 3'
    },
    { src: '/images/image_gallery/bw/10bw.jpg',
      srcBig: '/images/image_gallery/bw/big/10bw.jpg',
      category: 'bw',
      index: 45,
      title: '',
      position: 'bw column 3'
    },
    { src: '/images/image_gallery/bw/11bw.jpg',
      srcBig: '/images/image_gallery/bw/big/11bw.jpg',
      category: 'bw',
      index: 46,
      title: '',
      position: 'bw column 3'
    },
    { src: '/images/image_gallery/bw/12bw.jpg', 
      srcBig: '/images/image_gallery/bw/big/12bw.jpg',
      category: 'bw',
      index: 47,
      title: '',
      position: 'bw column 3'
    },
    { src: '/images/image_gallery/bw/13bw.jpg', 
      srcBig: '/images/image_gallery/bw/big/13bw.jpg', 
      category: 'bw' ,
      index: 48,
      title: '',
      position: 'bw column 2'
    },
    { src: '/images/image_gallery/portraits/1.jpg', 
      srcBig: '/images/image_gallery/portraits/big/1.jpg',
      category: 'portraits' ,
      index: 49,
      title: '',
      position: 'portraits column 1'
    },
    { src: '/images/image_gallery/portraits/2.jpg', 
      srcBig: '/images/image_gallery/portraits/big/2.jpg', 
      category: 'portraits' ,
      index: 50,
      title: '',
      position: 'portraits column 1'
    },
    { src: '/images/image_gallery/portraits/3.jpg', 
      srcBig: '/images/image_gallery/portraits/big/3.jpg', 
      category: 'portraits' ,
      index: 51,
      title: '',
      position: 'portraits column 1'
    },
    { src: '/images/image_gallery/portraits/4.jpg', 
      srcBig: '/images/image_gallery/portraits/big/4.jpg',
      category: 'portraits' ,
      index: 52,
      title: '',
      position: 'portraits column 1'
    },
    { src: '/images/image_gallery/portraits/5.jpg', 
      srcBig: '/images/image_gallery/portraits/big/5.jpg',
      category: 'portraits' ,
      index: 53,
      title: '',
      position: 'portraits column 1'
    },
    { src: '/images/image_gallery/portraits/6.jpg', 
      srcBig: '/images/image_gallery/portraits/big/6.jpg',
      category: 'portraits' ,
      index: 54,
      title: '',
      position: 'portraits column 2'
    },
    { src: '/images/image_gallery/portraits/7.jpg', 
      srcBig: '/images/image_gallery/portraits/big/7.jpg',
      category: 'portraits' ,
      index: 55,
      title: '',
      position: 'portraits column 2'
    },
    { src: '/images/image_gallery/portraits/8.jpg', 
      srcBig: '/images/image_gallery/portraits/big/8.jpg',
      category: 'portraits' ,
      index: 56,
      title: '',
      position: 'portraits column 2'
    },
    { src: '/images/image_gallery/portraits/9.jpg', 
      srcBig: '/images/image_gallery/portraits/big/9.jpg',
      category: 'portraits' ,
      index: 57,
      title: '',
      position: 'portraits column 2'
    },
    { src: '/images/image_gallery/portraits/10.jpg', 
      srcBig: '/images/image_gallery/portraits/big/10.jpg', 
      category: 'portraits' ,
      index: 58,
      title: '',
      position: 'portraits column 3'
    },
    { src: '/images/image_gallery/portraits/11.jpg', 
      srcBig: '/images/image_gallery/portraits/big/11.jpg', 
      category: 'portraits' ,
      index: 59,
      title: '',
      position: 'portraits column 3'
    },
    { src: '/images/image_gallery/portraits/12.jpg', 
      srcBig: '/images/image_gallery/portraits/big/12.jpg',
      category: 'portraits' ,
      index: 60,
      title: '',
      position: 'portraits column 3'
    },
    { src: '/images/image_gallery/portraits/13.jpg', 
      srcBig: '/images/image_gallery/portraits/big/13.jpg',
      category: 'portraits' ,
      index: 61,
      title: '',
      position: 'portraits column 3'
    }
  ];

  export default photos;
