const photos = [
    { src: '/images/image_gallery/compart/1angels.jpg',
      category: 'compart',
      index: 0,
      title: '',
      position: 'compart column 1' 
    },
    { src: '/images/image_gallery/compart/2buddah.jpg',
      category: 'compart',
      index: 1,
      title: '',
      position: 'compart column 1' 
    },
    { src: '/images/image_gallery/compart/3broken.jpg',
      category: 'compart',
      index: 2,
      title: '',
      position: 'compart column 1' 
    },
    { src: '/images/image_gallery/compart/4captain.jpg',
      category: 'compart',
      index: 3,
      title: '',
      position: 'compart column 1' 
    },
    { src: '/images/image_gallery/compart/5chakras.jpg',
      category: 'compart',
      index: 4,
      title: '',
      position: 'compart column 1' 
    },
    { src: '/images/image_gallery/compart/6planet.jpg',
      category: 'compart',
      index: 5,
      title: '',
      position: 'compart column 1' 
    },
    { src: '/images/image_gallery/compart/7cocoon.jpg',
      category: 'compart',
      index: 6,
      title: '',
      position: 'compart column 1' 
    },
    { src: '/images/image_gallery/compart/8colors.jpg',
      category: 'compart',
      index: 7,
      title: '',
      position: 'compart column 1' 
    },
    { src: '/images/image_gallery/compart/9dance1.jpg',
      category: 'compart',
      index: 8, 
      title: '',
      position: 'compart column 1'
    },
    { src: '/images/image_gallery/compart/10depression.jpg',
      category: 'compart',
      index: 9, 
      title: '',
      position: 'compart column 1'
    },
    { src: '/images/image_gallery/compart/11dreamcatcher.jpg',
      category: 'compart',
      index: 10, 
      title: '',
      position: 'compart column 1'
    },
    { src: '/images/image_gallery/compart/12fire.jpg',
      category: 'compart',
      index: 11, 
      title: '',
      position: 'compart column 1'
    },
    { src: '/images/image_gallery/compart/13forest_miao.jpg',
      category: 'compart',
      index: 12, 
      title: '',
      position: 'compart column 1'
    },
    { src: '/images/image_gallery/compart/14future.jpg',
      category: 'compart',
      index: 13, 
      title: '',
      position: 'compart column 2'
    },
    { src: '/images/image_gallery/compart/15gym.jpg',
      category: 'compart',
      index: 14, 
      title: '',
      position: 'compart column 2'
    },
    { src: '/images/image_gallery/compart/16hairball.jpg',
      category: 'compart',
      index: 15, 
      title: '',
      position: 'compart column 2'
    },
    { src: '/images/image_gallery/compart/17hands.jpg',
      category: 'compart',
      index: 16, 
      title: '',
      position: 'compart column 2'
    },
    { src: '/images/image_gallery/compart/18inside.jpg',
      category: 'compart',
      index: 17, 
      title: '',
      position: 'compart column 2'
    },
    { src: '/images/image_gallery/compart/19kuanYin.jpg',
      category: 'compart',
      index: 18, 
      title: '',
      position: 'compart column 2'
    },
    { src: '/images/image_gallery/compart/20lace.jpg',
      category: 'compart',
      index: 19, 
      title: '',
      position: 'compart column 2'
    },
    { src: '/images/image_gallery/compart/21moonlight.jpg',
      category: 'compart',
      index: 20, 
      title: '',
      position: 'compart column 2'
    },
    { src: '/images/image_gallery/compart/22night.jpg',
      category: 'compart',
      index: 21, 
      title: '',
      position: 'compart column 2'
    },
    { src: '/images/image_gallery/compart/23night.jpg',
      category: 'compart',
      index: 22, 
      title: '',
      position: 'compart column 2'
    },
    { src: '/images/image_gallery/compart/24night.jpg',
      category: 'compart',
      index: 23, 
      title: '',
      position: 'compart column 2'
    },
    { src: '/images/image_gallery/compart/25evening.jpg',
      category: 'compart',
      index: 24, 
      title: '',
      position: 'compart column 3'
    },
    { src: '/images/image_gallery/compart/26smoke.jpg',
      category: 'compart',
      index: 25, 
      title: '',
      position: 'compart column 3'
    },
    { src: '/images/image_gallery/compart/27solar_eclipse.jpg',
      category: 'compart',
      index: 26, 
      title: '',
      position: 'compart column 3'
    },
    { src: '/images/image_gallery/compart/28solitude.jpg',
      category: 'compart',
      index: 27, 
      title: '',
      position: 'compart column 3'
    },
    { src: '/images/image_gallery/compart/29somewhere.jpg',
      category: 'compart',
      index: 28, 
      title: '',
      position: 'compart column 3'
    },
    { src: '/images/image_gallery/compart/30somewhere.jpg',
      category: 'compart',
      index: 29, 
      title: '',
      position: 'compart column 3'
    },
    { src: '/images/image_gallery/compart/31summer_day.jpg',
      category: 'compart',
      index: 30, 
      title: '',
      position: 'compart column 3'
    },
    { src: '/images/image_gallery/compart/32summer.jpg',
      category: 'compart',
      index: 31, 
      title: '',
      position: 'compart column 3'
    },
    { src: '/images/image_gallery/compart/33thaughts.jpg',
      category: 'compart',
      index: 32, 
      title: '',
      position: 'compart column 3'
    },
    { src: '/images/image_gallery/compart/34wall.jpg',
      category: 'compart',
      index: 33, 
      title: '',
      position: 'compart column 3'
    },
    { src: '/images/image_gallery/compart/35water.jpg',
      category: 'compart',
      index: 34, 
      title: '',
      position: 'compart column 3'
    },
    { src: '/images/image_gallery/compart/36water.jpg',
      category: 'compart',
      index: 35, 
      title: '',
      position: 'compart column 3'
    },
    { src: '/images/image_gallery/bw/1bw.jpg',
      category: 'bw',
      index: 36,
      title: '',
      position: 'bw column 1'
    },
    { src: '/images/image_gallery/bw/2bw.jpg',
      category: 'bw',
      index: 37,
      title: '',
      position: 'bw column 1'
    },
    { src: '/images/image_gallery/bw/3bw.jpg',
      category: 'bw',
      index: 38,
      title: '',
      position: 'bw column 1'
    },
    { src: '/images/image_gallery/bw/4bw.jpg',
      category: 'bw',
      index: 39,
      title: '',
      position: 'bw column 1'
    },
    { src: '/images/image_gallery/bw/5bw.jpg',
      category: 'bw',
      index: 40,
      title: '',
      position: 'bw column 2'
    },
    { src: '/images/image_gallery/bw/6bw.jpg',
      category: 'bw',
      index: 41,
      title: '',
      position: 'bw column 2'
    },
    { src: '/images/image_gallery/bw/7bw.jpg',
      category: 'bw',
      index: 42,
      title: '',
      position: 'bw column 2'
    },
    { src: '/images/image_gallery/bw/8bw.jpg',
      category: 'bw',
      index: 43,
      title: '',
      position: 'bw column 2'
    },
    { src: '/images/image_gallery/bw/9bw.jpg',
      category: 'bw',
      index: 44,
      title: '',
      position: 'bw column 3'
    },
    { src: '/images/image_gallery/bw/10bw.jpg',
      category: 'bw',
      index: 45,
      title: '',
      position: 'bw column 3'
    },
    { src: '/images/image_gallery/bw/11bw.jpg',
      category: 'bw',
      index: 46,
      title: '',
      position: 'bw column 3'
    },
    { src: '/images/image_gallery/bw/12bw.jpg', 
      category: 'bw',
      index: 47,
      title: '',
      position: 'bw column 3'
    },
    { src: '/images/image_gallery/bw/13bw.jpg', 
      category: 'bw' ,
      index: 48,
      title: '',
      position: 'bw column 2'
    },
    { src: '/images/image_gallery/portraits/1.jpg', 
      category: 'portraits' ,
      index: 49,
      title: '',
      position: 'portraits column 1'
    },
    { src: '/images/image_gallery/portraits/2.jpg', 
      category: 'portraits' ,
      index: 50,
      title: '',
      position: 'portraits column 1'
    },
    { src: '/images/image_gallery/portraits/3.jpg', 
      category: 'portraits' ,
      index: 51,
      title: '',
      position: 'portraits column 1'
    },
    { src: '/images/image_gallery/portraits/4.jpg', 
      category: 'portraits' ,
      index: 52,
      title: '',
      position: 'portraits column 1'
    },
    { src: '/images/image_gallery/portraits/5.jpg', 
      category: 'portraits' ,
      index: 53,
      title: '',
      position: 'portraits column 1'
    },
    { src: '/images/image_gallery/portraits/6.jpg', 
      category: 'portraits' ,
      index: 54,
      title: '',
      position: 'portraits column 2'
    },
    { src: '/images/image_gallery/portraits/7.jpg', 
      category: 'portraits' ,
      index: 55,
      title: '',
      position: 'portraits column 2'
    },
    { src: '/images/image_gallery/portraits/8.jpg', 
      category: 'portraits' ,
      index: 56,
      title: '',
      position: 'portraits column 2'
    },
    { src: '/images/image_gallery/portraits/9.jpg', 
      category: 'portraits' ,
      index: 57,
      title: '',
      position: 'portraits column 2'
    },
    { src: '/images/image_gallery/portraits/10.jpg', 
      category: 'portraits' ,
      index: 58,
      title: '',
      position: 'portraits column 3'
    },
    { src: '/images/image_gallery/portraits/11.jpg', 
      category: 'portraits' ,
      index: 59,
      title: '',
      position: 'portraits column 3'
    },
    { src: '/images/image_gallery/portraits/12.jpg', 
      category: 'portraits' ,
      index: 60,
      title: '',
      position: 'portraits column 3'
    },
    { src: '/images/image_gallery/portraits/13.jpg', 
      category: 'portraits' ,
      index: 61,
      title: '',
      position: 'portraits column 3'
    },
    { src: '/images/image_gallery/shamans/1.jpg', 
      category: 'portraits' ,
      index: 62,
      title: '',
      position: 'shamans column 1'
    },
    { src: '/images/image_gallery/shamans/2.jpg', 
      category: 'portraits' ,
      index: 63,
      title: '',
      position: 'shamans column 1'
    },
    { src: '/images/image_gallery/shamans/3.jpg', 
      category: 'portraits' ,
      index: 64,
      title: '',
      position: 'shamans column 1'
    },
    { src: '/images/image_gallery/shamans/4.jpg', 
      category: 'portraits' ,
      index: 65,
      title: '',
      position: 'shamans column 1'
    },
    { src: '/images/image_gallery/shamans/5.jpg', 
      category: 'portraits' ,
      index: 66,
      title: '',
      position: 'shamans column 1'
    },
    { src: '/images/image_gallery/shamans/6.jpg', 
      category: 'portraits' ,
      index: 67,
      title: '',
      position: 'shamans column 2'
    },
    { src: '/images/image_gallery/shamans/7.jpg', 
      category: 'portraits' ,
      index: 68,
      title: '',
      position: 'shamans column 2'
    },
    { src: '/images/image_gallery/shamans/8.jpg', 
      category: 'portraits' ,
      index: 69,
      title: '',
      position: 'shamans column 2'
    },
    { src: '/images/image_gallery/shamans/9.jpg', 
      category: 'portraits' ,
      index: 70,
      title: '',
      position: 'shamans column 2'
    },
    { src: '/images/image_gallery/shamans/10.jpg', 
      category: 'portraits' ,
      index: 71,
      title: '',
      position: 'shamans column 2'
    },
    { src: '/images/image_gallery/shamans/11.jpg', 
      category: 'portraits' ,
      index: 72,
      title: '',
      position: 'shamans column 3'
    },
    { src: '/images/image_gallery/shamans/12.jpg', 
      category: 'portraits' ,
      index: 73,
      title: '',
      position: 'shamans column 3'
    },
    { src: '/images/image_gallery/shamans/13.jpg', 
      category: 'portraits' ,
      index: 74,
      title: '',
      position: 'shamans column 3'
    },
    { src: '/images/image_gallery/shamans/14.jpg', 
      category: 'portraits' ,
      index: 75,
      title: '',
      position: 'shamans column 3'
    },
    { src: '/images/image_gallery/shamans/15.jpg', 
      category: 'portraits' ,
      index: 76,
      title: '',
      position: 'shamans column 3'
    },
  ];

  export default photos;
